[package]
distribution = "2201.9.2"
org = "ballerinax"
name = "aws.marketplace.mpe"
version = "@toml.version@"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["AWS", "Marketplace", "Cloud/Subscriptions", "Entitlement Management"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-aws.marketplace.mpe"

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
groupId = "io.ballerina.lib"
artifactId = "aws.marketplace.mpe-native"
version = "@project.version@"
path = "../native/build/libs/aws.marketplace.mpe-native-@project.version@.jar"
